### ISSUE TITLE
Issue with Tensorflow Version 0.12.0

### ISSUE THREAD

**Issue by pinakirsarkar** [dlaptev/TI-pooling#3] opened 2017-03-30 20:01 UTC
![doubt](https://cloud.githubusercontent.com/assets/26071294/24523582/208d13f8-15b1-11e7-9b64-1e5620e45921.png)

**Comment by dlaptev** [comment] 2017-03-31 22:27
Hey @pinakirsarkar, thanks for your interest in TI-pooling and thanks for reporting the issue. Unfortunately, we cannot reproduce the problem with our current setup...

Does the error message also persist when you update TensorFlow to version 1.0? If so, could you give us more details? For example, could you copy-paste the full error message (with the full call stack)? Thanks!

**Comment by matrixBT** [comment] 2017-04-02 19:12
Hi @dlaptev. Tensor flow is not getting installed in our systems. Its saying "Could not find a tensorflow version satisfying this requirements". Is there any Keras/Theano Implementation for this TI POOLING. Thanks.!!!

**Comment by dlaptev** [comment] 2017-04-02 19:27
Hi @HelloMrBk, as for TensorFlow, are you sure your `pip` is upgraded? Running `pip install --upgrade pip` could solve the problem. Otherwise, please try to follow [the official instructions](https://www.tensorflow.org/install/) and [this discussion](http://stackoverflow.com/questions/38896424/tensorflow-not-found-in-pip).

As for Keras/Theano implementations, we do not have them, and currently I am not sure if anyone else is implementing those. But we have Torch implementation in this repository that could be helpful.

**Comment by dlaptev** [comment] 2017-04-08 14:30
I will close the issue for now. Please feel free to reopen in case you still have any questions.

**Closed as completed by dlaptev** 2017-04-08 14:30 UTC
